# -*- coding: utf-8 -*-
"""hexsoftware task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1sMMdnQTTwoRgdUd8kvahkVCu7V3rHB
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input, decode_predictions
from tensorflow.keras.preprocessing import image

# Load Pretrained Model
model = MobileNetV2(weights='imagenet')

# Load Image
img_path = '/content/cat 2.jpeg'  # <-- Replace with your image path
img = image.load_img(img_path, target_size=(224, 224))

# Convert Image to Array
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)

# Preprocess Image
img_array = preprocess_input(img_array)

# Predict
predictions = model.predict(img_array)

# Decode Predictions
decoded = decode_predictions(predictions, top=3)[0]

print("Top Predictions:")
for i, (imagenetID, label, probability) in enumerate(decoded):
    print(f"{i+1}: {label} ({probability*100:.2f}%)")

